# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    strategy:
      fail-fast: false
      matrix:
        version: [4.0.1-stable]
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Download Godot
        run: |
          curl https://github.com/godotengine/godot/releases/download/4.0.1-stable/Godot_${{ matrix.version }}_linux.x86_64.zip | unzip -O /dev/stdin > godot &&
          chmod +x godot
      - name: Check uuid.gd
        run: ./godot -c -s uuid.gd
      - name: Run tests
        run: ./godot -s test.gd
